### ISSUE TITLE
new compilation error

### ISSUE THREAD

**Issue by GunpowderGuy** [llvm-hs/llvm-hs-pretty#92]
After fixing the previously reported error : https://github.com/llvm-hs/llvm-hs-pretty/issues/91

i encountered the following one

llvm-hs-pretty> build with ghc-9.6.6
llvm-hs-pretty> Preprocessing library for llvm-hs-pretty-0.9.0.0..
llvm-hs-pretty> Building library for llvm-hs-pretty-0.9.0.0..
llvm-hs-pretty> [1 of 2] Compiling LLVM.Pretty.Typed
llvm-hs-pretty> 
llvm-hs-pretty> /tmp/stack-203a4bfe0349ffa9/llvm-hs-pretty-0.9.0.0/src/LLVM/Pretty/Typed.hs:58:11: error: [GHC-76037]
llvm-hs-pretty>     Not in scope: data constructor ‘C.UDiv’
llvm-hs-pretty>     NB: the module ‘LLVM.AST.Constant’ does not export ‘UDiv’.
llvm-hs-pretty>     Suggested fix:
llvm-hs-pretty>       Perhaps use ‘C.FDiv’ (imported from LLVM.AST.Constant)
llvm-hs-pretty>    |
llvm-hs-pretty> 58 |   typeOf (C.UDiv {..})    = typeOf operand0
llvm-hs-pretty>    |           ^^^^^^
llvm-hs-pretty> 
llvm-hs-pretty> /tmp/stack-203a4bfe0349ffa9/llvm-hs-pretty-0.9.0.0/src/LLVM/Pretty/Typed.hs:59:11: error: [GHC-76037]
llvm-hs-pretty>     Not in scope: data constructor ‘C.SDiv’
llvm-hs-pretty>     NB: the module ‘LLVM.AST.Constant’ does not export ‘SDiv’.
llvm-hs-pretty>     Suggested fix:
llvm-hs-pretty>       Perhaps use ‘C.FDiv’ (imported from LLVM.AST.Constant)
llvm-hs-pretty>    |
llvm-hs-pretty> 59 |   typeOf (C.SDiv {..})    = typeOf operand0
llvm-hs-pretty>    |           ^^^^^^
llvm-hs-pretty> 
llvm-hs-pretty> /tmp/stack-203a4bfe0349ffa9/llvm-hs-pretty-0.9.0.0/src/LLVM/Pretty/Typed.hs:95:11: error: [GHC-76037]
llvm-hs-pretty>     Not in scope: data constructor ‘C.ExtractValue’
llvm-hs-pretty>     NB: the module ‘LLVM.AST.Constant’ does not export ‘ExtractValue’.
llvm-hs-pretty>    |
llvm-hs-pretty> 95 |   typeOf (C.ExtractValue {..})    = extractValueType indices' (typeOf aggregate)
llvm-hs-pretty>    |           ^^^^^^^^^^^^^^
llvm-hs-pretty> 
llvm-hs-pretty> /tmp/stack-203a4bfe0349ffa9/llvm-hs-pretty-0.9.0.0/src/LLVM/Pretty/Typed.hs:96:11: error: [GHC-76037]
llvm-hs-pretty>     Not in scope: data constructor ‘C.InsertValue’
llvm-hs-pretty>     NB: the module ‘LLVM.AST.Constant’ does not export ‘InsertValue’.
llvm-hs-pretty>    |
llvm-hs-pretty> 96 |   typeOf (C.InsertValue {..})     = typeOf aggregate
llvm-hs-pretty>    |           ^^^^^^^^^^^^^
llvm-hs       > Error: setup: '/usr/local/bin/llvm-config' exited with an error:
llvm-hs       > llvm-config: error: libLLVM-16.so is missing
llvm-hs       >
